# Generated by Django 3.0.4 on 2020-03-09 10:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20200309_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(default='/static/images/person_placeholder.jpg', max_length=255, verbose_name='profile_photo'),
        ),
    ]
